### ISSUE TITLE
Having trouble with rust-bio

### ISSUE THREAD

**Issue by adam-spencer** [Sheffield-iGEM/syn-zeug#43]
My (late) start has been impeded by some issue with the `rust-bio` submodule - I'm sure this is just a me-problem but I'm not sure exactly how to fix it.

When building the syn-zeug crate I get a 101 error due to a missing Cargo.toml in `rust-bio/` - the directory is also empty after my latest pull from the repo. I assume I need to install the `rust-bio` submodule, would just like some help with this.

**Comment by adam-spencer** [comment]
Had a looksie and realised I need to do some git submodule stuff - now running into a `publickey` issue with GH, will close this once all is sorted.

**Comment by adam-spencer** [comment]
All sorted, never used git submodules before. A learning experience I suppose.

**Comment by TheLostLambda** [comment]
No worries! Sorry for the trouble! I didn't want to have to fork the project, but it just lacked a few tiny things we needed. I'm working on up-streaming the changes now though.

Let me know if there is anything more you need!
